### ISSUE TITLE
PWA Offline Page Code Doesn't Work

### ISSUE THREAD

**Issue by DanJ210** [pwa-builder/pwabuilder-snippits#2]
Uncaught (in promise) TypeError: Request Failed

Code isn't working. Specifically on the line `return cache.add(new Response(offlineFallbackPage));`

```
self.addEventListener("install", function (event) {
    console.log("[PWA Builder] Install Event processing");
    event.waitUntil(
        caches.open(CACHE).then(function (cache) {
            console.log("[PWA Builder] Cached offline page during install");
            if (offlineFallbackPage === "offline.html") {
                return cache.add(new Response(offlineFallbackPage));
            }
            console.log("done installing");
            return cache.add(offlineFallbackPage);
        })
    );
});
```

**Comment by benmassaoud** [comment]
Hi, 
Did you found a solution for that?

**Comment by nssk1999** [comment]
### **i found a solution for it**

const staticCacheName = 'site-static-v1.0.3';
const dynamicCacheName = 'site-dynamic-v1.0';
const assets = [
  '/',
  '/index.html'
];

// cache size limit function
const limitCacheSize = (name, size) => {
  caches.open(name).then(cache => {
    cache.keys().then(keys => {
      if(keys.length > size){
        cache.delete(keys[0]).then(limitCacheSize(name, size));
      }
    });
  });
};


// install event
self.addEventListener('install', evt => {
  //console.log('service worker installed');
  evt.waitUntil(
    caches.open(staticCacheName).then((cache) => {
      console.log('caching shell assets');
      cache.addAll(assets);
    })
  );
});

// activate event
self.addEventListener('activate', evt => {
  //console.log('service worker activated');
  evt.waitUntil(
    caches.keys().then(keys => {
      //console.log(keys);
      return Promise.all(keys
        .filter(key => key !== staticCacheName && key !== dynamicCacheName)
        .map(key => caches.delete(key))
      );
    })
  );
});

// fetch event
self.addEventListener('fetch', evt => {
  if(evt.request.url.indexOf('firestore.googleapis.com') === -1){
    evt.respondWith(
      caches.match(evt.request).then(cacheRes => {
        return cacheRes || fetch(evt.request).then(fetchRes => {
          return caches.open(dynamicCacheName).then(cache => {
            cache.put(evt.request.url, fetchRes.clone());
            // check cached items size
            limitCacheSize(dynamicCacheName, 15);
            return fetchRes;
          })
        });
      }).catch(() => {
        if(evt.request.url.indexOf('.html') > -1){
          return caches.match('/pages/fallback.html');
        } 
      })
    );
  }
});
